export {default as LogoIcon} from "./favicon.svg";
export {default as PinIcon} from "./pin.svg";
export {default as MarkerIcon} from "./marker.svg";
export {default as PlaneIcon} from "./planeIcon.svg";
export {default as CityIcon} from "./cityIcon.svg";
export {default as FlagIcon} from "./flagIcon.svg";
export {default as HashtagIcon} from "./hashtagIcon.svg";
export {default as CoordinatesIcon} from "./coordinatesIcon.svg";
export {default as PathIcon} from "./pathIcon.svg";
export {default as ArrowIcon} from "./arrowIcon.svg";
export {default as MarkersIcon} from "./markersIcon.svg";
export {default as InfoIcon} from "./infoIcon.svg";
export {default as FacebookIcon} from "./facebookIcon.svg";
export {default as InstagramIcon} from "./instagramIcon.svg";
export {default as TwitterIcon} from "./twitterIcon.svg";
export { default as SearchIcon } from "./searchIcon.svg";
export { default as IATAIcon } from "./iataIcon.svg";
export { default as DirectionIcon } from "./directionIcon.svg";
export { default as PassengersIcon } from "./passengersIcon.svg";
export { default as AirportsIcon } from "./airportsIcon.svg";
export { default as CityColoredIcon } from "./cityColoredIcon.svg";
export { default as ClockIcon } from "./clockIcon.svg";

export * from "./languages";
