/* eslint-disable @typescript-eslint/no-non-null-assertion */
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { HomePage } from "~/src/components/pages/Home";
import { api } from "~/src/utils/api";

const Airport: NextPage = () => {
  const router = useRouter();
  const airportID = router.query.airport && +router.query.airport;
  console.log(airportID);

  const { data: airport, isSuccess } = api.airport?.getAirport.useQuery({
    airport: airportID || 0,
  });

  console.log(airport);

  return isSuccess ? (
    <>
      <Head>
        <title>Explore Locations</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <HomePage name={airport[0]!.Name} />
    </>
  ) : (
    <></>
  );
};

export default Airport;
