import { type NextPage } from "next";
import Head from "next/head";
import { HomePage } from "../components/pages/HomePage";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Explore Locations</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <HomePage />
    </>
  );
};

export default Home;
